New content
ReactSSA/recursos-para-desenvolvimento-web pull request #9
Opened 2019-02-09 17:50 UTC by crisgon

- GraphQl Posts in portuguese
- Git and Github course in portuguese

2019-02-10 06:32 UTC, lucianomlima requested changes

2019-02-10 06:32 UTC, lucianomlima commented on README.md
> +- [GraphQL —A flexibilidade do formato de dados](https://medium.com/trainingcenter/graphql-os-dados-no-formato-requisitado-964f5555d467) :brazil: :page_facing_up: :free:
Add a space between dash and A, and you're ready to go!
```suggestion
- [GraphQL — A flexibilidade do formato de dados](https://medium.com/trainingcenter/graphql-os-dados-no-formato-requisitado-964f5555d467) :brazil: :page_facing_up: :free:
```

2019-02-10 16:08 UTC, crisgon commented
Feito!

2019-02-11 03:28 UTC, lucianomlima commented on README.md
> +- [GraphQL  —  Aprendendo na prática](https://medium.com/trainingcenter/graphql-aprendendo-na-pr%C3%A1tica-569a6866065b) :brazil: :page_facing_up: :free:
You put a extra space here 😆
```suggestion
- [GraphQL —  Aprendendo na prática](https://medium.com/trainingcenter/graphql-aprendendo-na-pr%C3%A1tica-569a6866065b) :brazil: :page_facing_up: :free:
```

2019-02-11 04:41 UTC, lucianomlima approved these changes
Nice!

2019-02-11 04:41 UTC, merged